serverAddr = "192.9.131.139"
serverPort = 7000

auth.method = "token"
auth.token = "mV+utY4BtKQRBR33+MhF3wi3LTooQh3oSMq0FeQojSM="


[[proxies]]
name = "sqldb"
type = "tcp"
localIP = "localhost"
localPort = 1433
remotePort = 1433

[[proxies]]
name = "postgresdb"
type = "tcp"
localIP = "localhost"
localPort = 5432
remotePort = 5432

[[proxies]]
name = "mysqldb"
type = "tcp"
localIP = "localhost"
localPort = 3306
remotePort = 3306
